
version: '4.32.0'

services:

    django:
      container_name: push_notification
      build: 
        context: ./push_notify
      command: uvicorn push_notify.asgi:application --host 0.0.0.0 --port 8000 --workers 4 --log-level debug --reload
      volumes:
        - ./push_notify:/app/
      ports:
        - 8001:8000
      env_file:
        - ./env_vars_django.txt
      # depends_on:
      #   - redis
      
