
version: '4.32.0'

services:

    django:
      container_name: push_notification
      build: 
        context: ./push_notify
      command: python3 manage.py runserver 0.0.0.0:8000
      volumes:
        - ./push_notify:/app/
      ports:
        - 8001:8000
      environment:
        - DEBUG=1
        - SECRET_KEY=082JDFS8848KHW38LF-233l0pkl
        - ALLOWED_HOSTS=localhost,127.0.0.1
      depends_on:
        - redis
