
version: '4.32.0'

services:

    django:
      container_name: push_notification
      build: 
        context: ./push_notify
      command: uvicorn push_notify.asgi:application --host 0.0.0.0 --port 8000 --workers 4 --log-level debug --reload
      volumes:
        - ./push_notify:/app/
      ports:
        - 8001:8000
      env_file:
        - ./env_vars_django.txt
      # depends_on:
      #   - redis
      
    rabbitmq:
      image: rabbitmq:4.0-rc-management
      restart: always
      container_name: rabbitmq
      ports:
        - 5672:5672
        - 15672:15672

    redis:
      image: redis:7.4-rc
      restart: always
      container_name: redis
      ports:
        - 6379:6379

    flower:
      image: mher/flower
      restart: always
      container_name: flower
      ports:
        - 5555:5555
      environment:
        - BROKER_URL=amqp://guest:guest@rabbitmq:5672/
      # command: flower --port=5555 --broker=amqp://guest:guest@rabbitmq:5672/

    celery:
      container_name: celery
      restart: always
      build:
        context: ./push_notify
      command: celery --app=push_notify worker -l INFO -B
      volumes:
        - ./push_notify:/app/
      env_file:
        - ./env_vars_django.txt